import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './localDashbord.css';
import {logout} from "../API/logout";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
    <div className="main">
      <div className="flex-item-left">
        <div className="min-h-screen flex flex-row bg-gray-100">
          <div className="flex flex-col w-56 bg-white rounded-r-3xl overflow-hidden">
            <div className="flex items-center justify-center h-20 shadow-md">
              <h1 className="text-3xl uppercase text-indigo-500">Logo</h1>
            </div>
            <ul className="flex flex-col py-4">
            <li>
                <a href="http://localhost:3000/dashbord/user" className="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                  <span className="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i className="bx bx-music"></i></span>
                  <span className="text-sm font-medium">My profile</span>
                </a>
              </li>
              <li>
                <a href="http://localhost:3000/dashbord/users" className="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                  <span className="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i className="bx bx-music"></i></span>
                  <span className="text-sm font-medium">Users</span>
                </a>
              </li>
              <li>
                <a href="http://localhost:3000/dashbord/hotels" className="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                  <span className="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i className="bx bx-drink"></i></span>
                  <span className="text-sm font-medium">Hotels</span>
                </a>
              </li>
              <li>
                <a href="http://localhost:3000/dashbord/restaurants" className="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                  <span className="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i className="bx bx-shopping-bag"></i></span>
                  <span className="text-sm font-medium">Restaurants</span>
                </a>
              </li>
              <li>
                <a href="http://localhost:3000/dashbord/famous_places" className="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                  <span className="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i className="bx bx-chat"></i></span>
                  <span className="text-sm font-medium">Famous_places</span>
                </a>
              </li>
              <li>
                <a href="http://localhost:3000/dashbord/addplace" className="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                  <span className="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i className="bx bx-user"></i></span>
                  <span className="text-sm font-medium">Add Place</span>
                </a>
              </li>
              <li>
                <a href="http://localhost:3000/dashbord/Activetrip" className="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                  <span className="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i className="bx bx-bell"></i></span>
                  <span className="text-sm font-medium">Active Trip</span>
                </a>
              </li>
              <li>
                <a href="http://localhost:3000/dashbord/Pendingtrip" className="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                  <span className="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i className="bx bx-bell"></i></span>
                  <span className="text-sm font-medium">Pending Trip</span>
                </a>
              </li>
              <li>
                <a href="http://localhost:3000/dashbord/MyTrips" className="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                  <span className="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i className="bx bx-bell"></i></span>
                  <span className="text-sm font-medium">All My Trips</span>
                </a>
              </li>
              <li>
                <a href="http://localhost:3000/dashbord/addTripF" className="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                  <span className="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i className="bx bx-bell"></i></span>
                  <span className="text-sm font-medium">Add Trip</span>
                </a>
              </li>
              <li>
                <a href="http://localhost:3000/dashbord/notifications" className="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                  <span className="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i className="bx bx-bell"></i></span>
                  <span className="text-sm font-medium">Notifications</span>
                </a>
              </li>
              <li>
                <a href="http://localhost:3000/dashbord/chargingWallet" className="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                  <span className="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i className="bx bx-bell"></i></span>
                  <span className="text-sm font-medium">Order charging for wallet</span>
                </a>
              </li>
              <li>
                <a href="#" onClick={logout} className="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                  <span className="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i className="bx bx-log-out"></i></span>
                  <span className="text-sm font-medium">Logout</span>
                </a>
              </li>
            </ul>
          </div>
        </div>
        </div>
        <div className="flex-item-right">
          {children}
        </div>
        </div>
      </body>
    </html>
  );
}
